import React, { useEffect, useMemo, useState } from "react";
import { getSlide1AndLastTextThumbs } from "./slideThumbs";

/**
 * PUBLIC_INTERFACE
 * PptxPreview provides a robust client-side preview surface for a PPTX blob URL.
 *
 * Rationale:
 * - Most browsers cannot natively render PPTX content in an iframe/object.
 * - We still try to embed for the browsers/environments that support it.
 * - We ALWAYS provide a user-visible fallback: a direct link that opens/downloads the PPTX.
 * - We additionally render a deterministic "thumbnail-like" preview for Slide 1 and the
 *   last slide by extracting slide text from the PPTX ZIP. This ensures the panel never
 *   looks blank even when the browser cannot render PPTX inline.
 *
 * This component does not modify the PPTX. It only displays and reads the already-generated bytes.
 */
export default function PptxPreview({
  url,
  filename,
  pptxBytes = null,
  debug = false,
  errorMessage = "",
  pipeline = null,
  onSelectAddMode = null,
  addMode = "dateOnly",
}) {
  const [hasLoadEvent, setHasLoadEvent] = useState(false);
  const [embedError, setEmbedError] = useState("");
  const [thumbs, setThumbs] = useState(null);
  const [thumbError, setThumbError] = useState("");

  useEffect(() => {
    setHasLoadEvent(false);
    setEmbedError("");
  }, [url]);

  useEffect(() => {
    let cancelled = false;

    async function loadThumbs() {
      setThumbError("");
      setThumbs(null);

      if (!pptxBytes) return;

      try {
        const data = await getSlide1AndLastTextThumbs(pptxBytes);
        if (cancelled) return;
        setThumbs(data);
      } catch (e) {
        if (cancelled) return;
        setThumbError(e instanceof Error ? e.message : String(e));
      }
    }

    loadThumbs();

    return () => {
      cancelled = true;
    };
  }, [pptxBytes]);

  const label = useMemo(() => filename || "Generated.pptx", [filename]);

  // Never render a blank surface:
  // - When URL exists: ALWAYS show the Open/Download link.
  // - When URL missing: show either an error (if provided) or a waiting message.
  const showError = Boolean(!url && errorMessage);

  if (!url) {
    return (
      <div className="pptx-preview">
        <div className="preview-toolbar" aria-label="Preview actions">
          <div className="hint">
            {showError
              ? "Preview could not be generated."
              : "Preview will appear here once the template is loaded and the PPTX is generated."}
          </div>
          {debug && pipeline ? (
            <div className="hint">
              Debug: <strong>{pipeline.step}</strong>
              {pipeline.detail ? (
                <>
                  {" "}
                  (<code>{pipeline.detail}</code>)
                </>
              ) : null}
            </div>
          ) : null}
        </div>

        <div className="empty-preview" role={showError ? "alert" : undefined}>
          {showError ? (
            <>
              <strong>Error:</strong> {errorMessage}
            </>
          ) : (
            "Waiting for generation output…"
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="pptx-preview">
      <div className="preview-toolbar" aria-label="Preview actions">
        <div className="preview-actions-row">
          <a className="btn btn-secondary" href={url} download={label}>
            Download / Open PPTX
          </a>

          <div className="add-mode">
            <div className="add-mode-label">Add remaining slides</div>
            <label className="radio" htmlFor="addModeDateOnly">
              <input
                id="addModeDateOnly"
                type="radio"
                name="addMode"
                value="dateOnly"
                checked={addMode === "dateOnly"}
                onChange={() => onSelectAddMode && onSelectAddMode("dateOnly")}
              />
              Date-only (locked)
            </label>
            <label className="radio" htmlFor="addModeSkillFactory">
              <input
                id="addModeSkillFactory"
                type="radio"
                name="addMode"
                value="skillFactory"
                checked={addMode === "skillFactory"}
                onChange={() =>
                  onSelectAddMode && onSelectAddMode("skillFactory")
                }
              />
              Skill Factory
            </label>
          </div>
        </div>

        <div className="hint">
          This panel always shows Slide 1 and the last slide. Inline PPTX rendering
          may still be unsupported in your browser; use “Download / Open PPTX” if
          needed.
          {debug ? (
            <>
              {" "}
              <span>
                (iframe load: <strong>{hasLoadEvent ? "fired" : "pending"}</strong>
                {embedError ? (
                  <>
                    {", error: "}
                    <strong>{embedError}</strong>
                  </>
                ) : null}
                {pipeline ? (
                  <>
                    {", pipeline: "}
                    <strong>{pipeline.step}</strong>
                  </>
                ) : null}
                )
              </span>
            </>
          ) : null}
        </div>
      </div>

      <div className="preview-frame-wrap preview-grid">
        <div className="slide-thumbs" aria-label="Slide thumbnails">
          <div className="slide-thumbs-title">Visible slides</div>

          {thumbError ? (
            <div className="empty-preview" role="alert">
              <strong>Thumbnail error:</strong> {thumbError}
            </div>
          ) : null}

          {!thumbs ? (
            <div className="empty-preview">Building thumbnails…</div>
          ) : (
            <div className="slide-thumb-list">
              <div className="slide-thumb" aria-label="Slide 1 thumbnail">
                <div className="slide-thumb-header">
                  <div className="slide-thumb-title">Slide 1</div>
                  <div className="slide-thumb-badge">date editable</div>
                </div>
                <div className="slide-thumb-body">
                  {thumbs.slide1.lines.length ? (
                    thumbs.slide1.lines.map((line, idx) => (
                      <div key={`s1-${idx}`} className="slide-thumb-line">
                        {line}
                      </div>
                    ))
                  ) : (
                    <div className="slide-thumb-line muted">(no text found)</div>
                  )}
                </div>
              </div>

              <div className="slide-thumb" aria-label="Last slide thumbnail">
                <div className="slide-thumb-header">
                  <div className="slide-thumb-title">
                    Last slide
                    {thumbs.last.index ? (
                      <span className="muted"> (#{thumbs.last.index})</span>
                    ) : null}
                  </div>
                  <div className="slide-thumb-badge locked">locked</div>
                </div>
                <div className="slide-thumb-body">
                  {thumbs.last.lines.length ? (
                    thumbs.last.lines.map((line, idx) => (
                      <div key={`sl-${idx}`} className="slide-thumb-line">
                        {line}
                      </div>
                    ))
                  ) : (
                    <div className="slide-thumb-line muted">(no text found)</div>
                  )}
                </div>
              </div>
            </div>
          )}

          {addMode === "skillFactory" ? (
            <div className="hint">
              Skill Factory is enabled. (Placeholder) Remaining slides will be
              added in a future update; Slide 1 date-only edit and the last slide
              remain protected.
            </div>
          ) : (
            <div className="hint">
              Date-only mode: only Slide 1 date is updated; last slide remains
              byte-identical.
            </div>
          )}
        </div>

        <div className="embed-preview">
          {/* Attempt iframe embed first. Some environments may at least show an Office prompt UI. */}
          <iframe
            title="PPTX Preview"
            className="preview-frame"
            src={url}
            onLoad={() => setHasLoadEvent(true)}
            onError={() => setEmbedError("iframe error")}
          />

          {/* Secondary attempt via <object> (sometimes behaves differently than iframe). */}
          <object
            className="preview-object"
            data={url}
            type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            aria-label="PPTX Object Preview"
            onError={() => setEmbedError("object error")}
          >
            <div className="empty-preview">
              Inline PPTX preview is not supported in this browser. Use the link
              above to open the generated file.
            </div>
          </object>
        </div>
      </div>
    </div>
  );
}
